#36 Added optional SOURCE_REFERENCE column
exasol/virtual-schema-common-document pull request #38
Opened 2020-10-06 15:53 UTC by jakobbraun

Closes #36

2020-10-06 15:57 UTC, jakobbraun commented
Implemented in:
* https://github.com/exasol/virtual-schema-common-document-files/pull/31

2020-10-07 07:26 UTC, morazow requested changes

2020-10-07 07:26 UTC, morazow commented on doc/changes/changes_3.0.0.md
> +  * Caused new EDML version 1.3.0
I am not sure sub points necessary here. Maybe you can add short description of column and notice to check the user guide for more info in summary section above.

2020-10-07 07:26 UTC, morazow commented on src/main/java/com/exasol/adapter/document/mapping/SourceReferenceColumnMapping.java
> + */
There is extra `is` before used. Could you also add `<p>` after the first sentence?

2020-10-07 07:26 UTC, morazow commented on src/main/java/com/exasol/adapter/document/mapping/SourceReferenceColumnMapping.java
> +        return DataType.createVarChar(2000, DataType.ExaCharset.UTF8);
Maybe add that is will be capped to 2000 characters in the user guide. Unlikely that paths exceeds it, but never know.

2020-10-07 07:26 UTC, morazow commented on doc/user_guide/edml_user_guide.md
> +The adapter will then automatically add a column named `SOURCE_REFERENCE`.
Mention also that it will be added to the end of the table.

2020-10-07 07:26 UTC, morazow commented on doc/changes/changes_3.0.0.md
> +  * Caused new EDML version 1.3.0
The version of new EDML should be `1.2.0`, right? I see it is 1.2.0 in deployment and also in code.

2020-10-07 08:11 UTC, morazow approved these changes

2020-10-07 08:19 UTC, merged